# Generated by Django 5.2.2 on 2025-06-30 17:03

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Номер должен быть в формате: '+79123456789' (11 цифр с кодом страны)", regex='^\\+7\\d{10}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telegram', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Ник должен начинаться с @ и содержать только буквы, цифры и _', regex='^@[A-Za-zА-Яа-я0-9_]+$')])),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_person', to='service_company.servicecompany')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Номер должен быть в формате: '+79123456789' (11 цифр с кодом страны)", regex='^\\+7\\d{10}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telegram', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Ник должен начинаться с @ и содержать только буквы, цифры и _', regex='^@[A-Za-zА-Яа-я0-9_]+$')])),
                ('region', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Номер должен быть в формате: '+79123456789' (11 цифр с кодом страны)", regex='^\\+7\\d{10}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telegram', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Ник должен начинаться с @ и содержать только буквы, цифры и _', regex='^@[A-Za-zА-Яа-я0-9_]+$')])),
                ('name', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(default=accounts.models.get_fault_manger, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='clients', to='accounts.manager')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Номер должен быть в формате: '+79123456789' (11 цифр с кодом страны)", regex='^\\+7\\d{10}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telegram', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Ник должен начинаться с @ и содержать только буквы, цифры и _', regex='^@[A-Za-zА-Яа-я0-9_]+$')])),
                ('position', models.CharField(blank=True, max_length=150, null=True)),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_master', to='service_company.servicecompany')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
