# Generated by Django 5.2.2 on 2025-07-09 14:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('complaints', '0001_initial'),
        ('service_company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Вид ТО',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_hours', models.IntegerField()),
                ('maintenance_date', models.DateField(blank=True, null=True)),
                ('work_order_number', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Номер заказ-наряда должен быть в формате: #2025-32КЕ5СИЛ', regex='^#[A-Za-zА-Яа-я0-9_ №\\-.]+$')])),
                ('work_order_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'Новая'), ('under_review', 'На рассмотрении'), ('in_progress', 'В процессе'), ('closed', 'ТО проведено'), ('complaint', 'Создана рекламация по причине неисправности'), ('rejected', 'Отклонена')], null=True)),
                ('service_company_respond', models.TextField(blank=True, null=True)),
                ('complaint_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.complaint')),
                ('service_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_company.servicecompany')),
                ('service_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.servicemaster')),
                ('maintenance_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technical_service.maintenancetype')),
            ],
        ),
    ]
