# Generated by Django 5.2.2 on 2025-07-20 13:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('complaints', '0001_initial'),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид ТО',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_hours', models.IntegerField(verbose_name='Наработка, м/час')),
                ('maintenance_date', models.DateField(blank=True, null=True, verbose_name='Дата проведения ТО')),
                ('work_order_number', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Номер заказ-наряда должен быть в формате: #2025-32КЕ5СИЛ', regex='^#[A-Za-zА-Яа-я0-9_ №\\-.]+$')], verbose_name='Номер заказ-наряда')),
                ('work_order_date', models.DateField(blank=True, null=True, verbose_name='Дата заказ-наряда')),
                ('status', models.CharField(blank=True, choices=[('new', 'Новая'), ('under_review', 'На рассмотрении'), ('in_progress', 'В процессе'), ('closed', 'ТО проведено'), ('complaint', 'Создана рекламация по причине неисправности'), ('rejected', 'Отклонена')], null=True, verbose_name='Статус')),
                ('service_company_respond', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('complaint_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.complaint', verbose_name='Номер рекламации')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='machines.machine', verbose_name='Машина')),
                ('service_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.servicecompany', verbose_name='Сервисная компания')),
                ('service_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.servicemaster', verbose_name='Мастер')),
                ('maintenance_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technical_service.maintenancetype', verbose_name='Вид ТО')),
            ],
        ),
    ]
