# Generated by Django 5.2.2 on 2025-07-10 10:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('complaints', '0002_alter_complaint_downtime_and_more'),
        ('machines', '0002_alter_driveaxletype_description_and_more'),
        ('service_company', '0001_initial'),
        ('technical_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='complaint_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.complaint', verbose_name='Номер рекламации'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведения ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technical_service.maintenancetype', verbose_name='Вид ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='operating_hours',
            field=models.IntegerField(verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_company.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company_respond',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.servicemaster', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новая'), ('under_review', 'На рассмотрении'), ('in_progress', 'В процессе'), ('closed', 'ТО проведено'), ('complaint', 'Создана рекламация по причине неисправности'), ('rejected', 'Отклонена')], null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='work_order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='work_order_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Номер заказ-наряда должен быть в формате: #2025-32КЕ5СИЛ', regex='^#[A-Za-zА-Яа-я0-9_ №\\-.]+$')], verbose_name='Номер заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='maintenancetype',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
