# Generated by Django 5.2.2 on 2025-07-09 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('service_company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Узел отказа',
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Способ восстановления',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField()),
                ('operating_hours', models.IntegerField()),
                ('failure_node_description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Новая'), ('under_review', 'На рассмотрении'), ('in_progress', 'В процессе ремонта'), ('resolved', 'Работы завершены'), ('closed', 'Закрыта'), ('rejected', 'Отклонена')], default='new')),
                ('used_spare_parts', models.TextField(blank=True, null=True)),
                ('recovery_date', models.DateField(blank=True, null=True)),
                ('downtime', models.CharField(blank=True, max_length=25, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='machines.machine')),
                ('service_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='service_company.servicecompany')),
                ('failure_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.failurenode')),
                ('recovery_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.recoverymethod')),
            ],
        ),
    ]
