# Generated by Django 5.2.2 on 2025-07-20 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Узел отказа',
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ восстановления',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='Дата отказа')),
                ('operating_hours', models.IntegerField(verbose_name='Наработка, м/час')),
                ('failure_node_description', models.TextField(verbose_name='Описание отказа')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('under_review', 'На рассмотрении'), ('in_progress', 'В процессе ремонта'), ('resolved', 'Работы завершены'), ('closed', 'Закрыта'), ('rejected', 'Отклонена')], default='new', verbose_name='Статус')),
                ('used_spare_parts', models.TextField(blank=True, null=True, verbose_name='Используемые запасные части')),
                ('recovery_date', models.DateField(blank=True, null=True, verbose_name='Дата восстановления')),
                ('downtime', models.CharField(blank=True, max_length=25, null=True, verbose_name='Время простоя техники')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='machines.machine', verbose_name='Машина')),
                ('service_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='accounts.servicecompany', verbose_name='Сервисная компания')),
                ('failure_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.failurenode', verbose_name='Узел отказа')),
                ('recovery_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.recoverymethod', verbose_name='Способ восстановления')),
            ],
        ),
    ]
