# Generated by Django 5.2.2 on 2025-07-10 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        ('machines', '0001_initial'),
        ('service_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='downtime',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Время простоя техники'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='failure_date',
            field=models.DateField(verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='failure_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.failurenode', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='failure_node_description',
            field=models.TextField(verbose_name='Описание отказа'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='machines.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='operating_hours',
            field=models.IntegerField(verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='recovery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата восстановления'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='recovery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.recoverymethod', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='service_company.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('under_review', 'На рассмотрении'), ('in_progress', 'В процессе ремонта'), ('resolved', 'Работы завершены'), ('closed', 'Закрыта'), ('rejected', 'Отклонена')], default='new', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='used_spare_parts',
            field=models.TextField(blank=True, null=True, verbose_name='Используемые запасные части'),
        ),
        migrations.AlterField(
            model_name='failurenode',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='failurenode',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recoverymethod',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recoverymethod',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
