# Generated by Django 5.2.2 on 2025-07-20 13:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveAxleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
            },
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель техники',
            },
        ),
        migrations.CreateModel(
            name='SteerAxleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
            },
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_contract_number_date', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Номер и дата договора должны быть в формате (разрешены буквы, цифры, дефис): №9999-999 01.01.2025', regex='^[A-Za-zА-Яа-я0-9_ №\\-.]+$')], verbose_name='Номер договора поставки')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee_end_customer', models.CharField(max_length=150, verbose_name='Грузополучатель (конечный потребитель)')),
                ('operating_address', models.CharField(max_length=150, verbose_name='Адрес поставки')),
                ('equipment', models.TextField(default='Стандарт', verbose_name='Комплектация')),
                ('machine_serial_number', models.CharField(max_length=50, unique=True, verbose_name='Заводской номер машины')),
                ('engine_serial_number', models.CharField(max_length=50, unique=True, verbose_name='Заводской номер двигателя')),
                ('transmission_serial_number', models.CharField(max_length=50, unique=True, verbose_name='Заводской номер трансмиссии')),
                ('drive_axle_serial_number', models.CharField(max_length=50, unique=True, verbose_name='Заводской номер ведущего моста')),
                ('steer_axle_serial_number', models.CharField(max_length=50, unique=True, verbose_name='Заводской номер управляемого моста')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='accounts.client', verbose_name='Клиент')),
                ('drive_axle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.driveaxletype', verbose_name='Модель ведущего моста')),
                ('engine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.enginetype', verbose_name='Модель двигателя')),
                ('service_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='accounts.servicecompany', verbose_name='Сервисная компания')),
                ('machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.machinetype', verbose_name='Модель техники')),
                ('steer_axle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.steeraxletype', verbose_name='Модель управляемого моста')),
                ('transmission_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.transmissiontype', verbose_name='Модель трансмиссии')),
            ],
        ),
    ]
