# Generated by Django 5.2.2 on 2025-07-09 12:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('service_company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveAxleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
            },
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Модель двигателя',
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Модель техники',
            },
        ),
        migrations.CreateModel(
            name='SteerAxleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
            },
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_contract_number_date', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Номер и дата договора должны быть в формате (разрешены буквы, цифры, дефис): №9999-999 01.01.2025', regex='^[A-Za-zА-Яа-я0-9_ №\\-.]+$')])),
                ('shipment_date', models.DateField()),
                ('consignee_end_customer', models.CharField(max_length=150)),
                ('operating_address', models.CharField(max_length=150)),
                ('equipment', models.TextField(default='Стандарт')),
                ('machine_serial_number', models.CharField(max_length=50, unique=True)),
                ('engine_serial_number', models.CharField(max_length=50, unique=True)),
                ('transmission_serial_number', models.CharField(max_length=50, unique=True)),
                ('drive_axle_serial_number', models.CharField(max_length=50, unique=True)),
                ('steer_axle_serial_number', models.CharField(max_length=50, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='accounts.client')),
                ('drive_axle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.driveaxletype')),
                ('engine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.enginetype')),
                ('service_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='service_company.servicecompany')),
                ('machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.machinetype')),
                ('steer_axle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.steeraxletype')),
                ('transmission_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.transmissiontype')),
            ],
        ),
    ]
