# Generated by Django 5.2.2 on 2025-07-10 10:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('machines', '0001_initial'),
        ('service_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveaxletype',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='driveaxletype',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='enginetype',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='enginetype',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='accounts.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='consignee_end_customer',
            field=models.CharField(max_length=150, verbose_name='Грузополучатель (конечный потребитель)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='drive_axle_serial_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Заводской номер ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='drive_axle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.driveaxletype', verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_serial_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Заводской номер двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.enginetype', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='equipment',
            field=models.TextField(default='Стандарт', verbose_name='Комплектация'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_serial_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Заводской номер машины'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.machinetype', verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='operating_address',
            field=models.CharField(max_length=150, verbose_name='Адрес поставки'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='service_company.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='shipment_date',
            field=models.DateField(verbose_name='Дата отгрузки с завода'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steer_axle_serial_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Заводской номер управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steer_axle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.steeraxletype', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='supply_contract_number_date',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Номер и дата договора должны быть в формате (разрешены буквы, цифры, дефис): №9999-999 01.01.2025', regex='^[A-Za-zА-Яа-я0-9_ №\\-.]+$')], verbose_name='Номер договора поставки'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission_serial_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Заводской номер трансмиссии'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machines.transmissiontype', verbose_name='Модель трансмиссии'),
        ),
        migrations.AlterField(
            model_name='machinetype',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='machinetype',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='steeraxletype',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='steeraxletype',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='transmissiontype',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='transmissiontype',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
